-- Crushly backend setup (generated by `npm run bundle:sql` — do not edit by hand).
-- Paste this whole file into the Supabase dashboard's SQL editor (New query →
-- Run) on a fresh project. It contains the schema, security rules and RPCs.
-- Demo data is NOT included; see seed.sql only if you want it locally.

create extension if not exists pgcrypto with schema extensions;

-- ================================ 20261008000001_init.sql

-- Crushly schema on Supabase (Postgres)
--
-- Domain ids are bigint identity values (the app's `number` ids). Supabase
-- Auth owns identity: `auth.users.id` (uuid) is linked to `profiles.auth_user_id`.
-- All timestamps are epoch milliseconds (bigint) to match the app's `types.ts`.
--
-- Privacy model: RLS keeps every member's raw rows private to themselves.
-- Cross-member reads happen only through SECURITY DEFINER functions (0002)
-- which serialize profiles exactly like the old API did — exact coordinates
-- and birthdates never leave the database.

-- ---------------------------------------------------------------- utilities

create or replace function public.now_ms() returns bigint
language sql stable as $$
  select (extract(epoch from now()) * 1000)::bigint
$$;

-- The signed-in member's domain id, or null when not signed in. (Defined after
-- the tables: SQL-language function bodies are checked at create time.)
-- create or replace function public.me_id() ... see below.

-- Error convention understood by the app's api client: status | code | message.
create or replace function public.crushly_fail(status integer, code text, message text) returns void
language plpgsql as $$
begin
  raise exception using
    message = format('__CRUSHLY__%s__%s__%s', status, coalesce(code, ''), message),
    errcode = 'P0001';
end $$;

-- ------------------------------------------------------------------- tables

create table public.profiles (
  id                    bigint generated always as identity primary key,
  auth_user_id          uuid not null unique references auth.users(id) on delete cascade,
  -- Denormalized from auth for scripts and admin tools; the app reads the auth email.
  email                 text not null default '',
  status                text not null default 'active' check (status in ('active', 'paused')),
  is_demo               boolean not null default false,
  plus_interest         boolean not null default false,
  name                  text not null default '',
  birthdate             text,                                   -- YYYY-MM-DD, never exposed
  pronouns              text not null default '',
  bio                   text not null default '',
  city                  text not null default '',
  lat                   real,                                   -- snapped to ~1 km, never exposed
  lng                   real,
  intentions            jsonb not null default '[]',
  interests             jsonb not null default '[]',
  languages             jsonb not null default '[]',
  relationship_intention text not null default '',
  lifestyle             jsonb not null default '{}',
  verification          text not null default 'none'
                          check (verification in ('none', 'pending', 'verified', 'rejected')),
  onboarded             boolean not null default false,
  last_active_at        bigint not null default public.now_ms(),
  created_at            bigint not null default public.now_ms(),
  updated_at            bigint not null default public.now_ms()
);

create table public.photos (
  id          bigint generated always as identity primary key,
  user_id     bigint not null references public.profiles(id) on delete cascade,
  url         text not null,               -- storage path in the `media` bucket
  position    integer not null default 0,
  created_at  bigint not null default public.now_ms()
);
create index photos_user_position_idx on public.photos (user_id, position, id);

create table public.preferences (
  user_id        bigint primary key references public.profiles(id) on delete cascade,
  age_min        integer not null default 18,
  age_max        integer not null default 45,
  max_distance   integer not null default 50,                  -- km; 0 = anywhere
  intentions     jsonb not null default '[]',
  interests      jsonb not null default '[]',
  verified_only  boolean not null default false
);

create table public.privacy (
  user_id            bigint primary key references public.profiles(id) on delete cascade,
  show_distance      boolean not null default true,
  show_online        boolean not null default true,
  read_receipts      boolean not null default true,
  discoverable       boolean not null default true,
  profile_visibility text not null default 'everyone'
                       check (profile_visibility in ('everyone', 'connections')),
  who_can_message    text not null default 'mutual'
                       check (who_can_message in ('everyone', 'crushes', 'mutual')),
  who_can_crush      text not null default 'everyone'
                       check (who_can_crush in ('everyone', 'verified')),
  show_age           boolean not null default true,
  show_city          boolean not null default true,
  incognito          boolean not null default false            -- Crushly Plus (not purchasable yet)
);

create table public.notification_settings (
  user_id          bigint primary key references public.profiles(id) on delete cascade,
  messages         boolean not null default true,
  crushes          boolean not null default true,
  moments          boolean not null default true,
  recommendations  boolean not null default false
);

create table public.crushes (
  from_id     bigint not null references public.profiles(id) on delete cascade,
  to_id       bigint not null references public.profiles(id) on delete cascade,
  deep        boolean not null default false,
  note        text,
  created_at  bigint not null default public.now_ms(),
  primary key (from_id, to_id),
  check (from_id <> to_id)
);
create index crushes_to_idx on public.crushes (to_id, created_at);

create table public.passes (
  from_id     bigint not null references public.profiles(id) on delete cascade,
  to_id       bigint not null references public.profiles(id) on delete cascade,
  created_at  bigint not null default public.now_ms(),
  primary key (from_id, to_id)
);

-- user_a is always the lower id (enforced by trigger).
create table public.connections (
  user_a      bigint not null references public.profiles(id) on delete cascade,
  user_b      bigint not null references public.profiles(id) on delete cascade,
  created_at  bigint not null default public.now_ms(),
  primary key (user_a, user_b),
  check (user_a < user_b)
);

create table public.conversations (
  id              bigint generated always as identity primary key,
  user_a          bigint not null references public.profiles(id) on delete cascade,
  user_b          bigint not null references public.profiles(id) on delete cascade,
  created_at      bigint not null default public.now_ms(),
  last_message_at bigint,
  closed          boolean not null default false,
  unique (user_a, user_b),
  check (user_a < user_b)
);

create table public.messages (
  id              bigint generated always as identity primary key,
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  sender_id       bigint not null references public.profiles(id) on delete cascade,
  kind            text not null default 'text'
                    check (kind in ('text', 'photo', 'voice', 'sticker', 'profile', 'moment_reply')),
  body            text not null default '',
  media_url       text,
  meta            jsonb not null default '{}',
  created_at      bigint not null default public.now_ms(),
  read_at         bigint
);
create index messages_conversation_idx on public.messages (conversation_id, id);

create table public.message_reactions (
  message_id  bigint not null references public.messages(id) on delete cascade,
  user_id     bigint not null references public.profiles(id) on delete cascade,
  kind        text not null default 'crush'
                check (kind in ('crush', 'laugh', 'fire', 'wow')),
  created_at  bigint not null default public.now_ms(),
  primary key (message_id, user_id)
);

create table public.moments (
  id          bigint generated always as identity primary key,
  user_id     bigint not null references public.profiles(id) on delete cascade,
  kind        text not null check (kind in ('text', 'photo')),
  body        text not null default '',
  media_url   text,
  style       text not null default 'noir'
                check (style in ('noir', 'champagne', 'crimson', 'midnight', 'emerald')),
  audience    text not null default 'everyone' check (audience in ('everyone', 'connections')),
  created_at  bigint not null default public.now_ms(),
  expires_at  bigint not null
);
create index moments_expires_idx on public.moments (expires_at);

create table public.moment_views (
  moment_id   bigint not null references public.moments(id) on delete cascade,
  user_id     bigint not null references public.profiles(id) on delete cascade,
  created_at  bigint not null default public.now_ms(),
  primary key (moment_id, user_id)
);

create table public.moment_reactions (
  moment_id   bigint not null references public.moments(id) on delete cascade,
  user_id     bigint not null references public.profiles(id) on delete cascade,
  kind        text not null check (kind in ('crush', 'fire', 'laugh', 'wow', 'clap')),
  created_at  bigint not null default public.now_ms(),
  primary key (moment_id, user_id)
);

create table public.notifications (
  id          bigint generated always as identity primary key,
  user_id     bigint not null references public.profiles(id) on delete cascade,
  kind        text not null
                check (kind in ('crush', 'deep_crush', 'mutual', 'message', 'moment_reply', 'moment_reaction',
                                'verified', 'verification_rejected')),
  actor_id    bigint references public.profiles(id) on delete set null,
  ref_id      bigint,
  body        text not null default '',
  created_at  bigint not null default public.now_ms(),
  read_at     bigint
);
create index notifications_user_idx on public.notifications (user_id, id);

create table public.blocks (
  blocker_id  bigint not null references public.profiles(id) on delete cascade,
  blocked_id  bigint not null references public.profiles(id) on delete cascade,
  created_at  bigint not null default public.now_ms(),
  primary key (blocker_id, blocked_id),
  check (blocker_id <> blocked_id)
);

create table public.reports (
  id            bigint generated always as identity primary key,
  reporter_id   bigint not null references public.profiles(id) on delete cascade,
  reported_id   bigint not null references public.profiles(id) on delete cascade,
  reason        text not null
                  check (reason in ('fake_profile', 'harassment', 'inappropriate_content', 'scam',
                                    'underage', 'hate_speech', 'threats_safety', 'other')),
  details       text not null default '',
  context       text not null default '',
  created_at    bigint not null default public.now_ms(),
  handled       boolean not null default false
);

create table public.verification_requests (
  id            bigint generated always as identity primary key,
  user_id       bigint not null references public.profiles(id) on delete cascade,
  selfie_path   text not null,             -- storage path in the private `verification` bucket
  pose          text not null,
  status        text not null default 'pending'
                  check (status in ('pending', 'approved', 'rejected', 'superseded')),
  created_at    bigint not null default public.now_ms(),
  reviewed_at   bigint
);

-- ---------------------------------------------------------------- triggers

create or replace function public.me_id() returns bigint
language sql stable security definer set search_path = public as $$
  select id from profiles where auth_user_id = auth.uid()
$$;

-- Keep connection / conversation pairs sorted (user_a < user_b).
create or replace function public.pair_normalize() returns trigger
language plpgsql as $$
begin
  if new.user_a > new.user_b then
    select new.user_b, new.user_a into new.user_a, new.user_b;
  end if;
  return new;
end $$;

create trigger connections_pair_normalize before insert or update on public.connections
  for each row execute function public.pair_normalize();
create trigger conversations_pair_normalize before insert or update on public.conversations
  for each row execute function public.pair_normalize();

-- Every new Supabase Auth user gets a full set of member rows.
create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
declare
  new_id bigint;
begin
  insert into profiles (auth_user_id, email, created_at, updated_at, last_active_at)
  values (new.id, coalesce(new.email, ''), public.now_ms(), public.now_ms(), public.now_ms())
  returning id into new_id;
  insert into preferences (user_id) values (new_id);
  insert into privacy (user_id) values (new_id);
  insert into notification_settings (user_id) values (new_id);
  return new;
end $$;

create trigger on_auth_user_created after insert on auth.users
  for each row execute function public.handle_new_user();

-- --------------------------------------------------------------- row security

alter table public.profiles enable row level security;
alter table public.photos enable row level security;
alter table public.preferences enable row level security;
alter table public.privacy enable row level security;
alter table public.notification_settings enable row level security;
alter table public.crushes enable row level security;
alter table public.passes enable row level security;
alter table public.connections enable row level security;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;
alter table public.message_reactions enable row level security;
alter table public.moments enable row level security;
alter table public.moment_views enable row level security;
alter table public.moment_reactions enable row level security;
alter table public.notifications enable row level security;
alter table public.blocks enable row level security;
alter table public.reports enable row level security;
alter table public.verification_requests enable row level security;

-- Members only ever read their own raw rows. Everything cross-member is served
-- by the SECURITY DEFINER functions in 0002_functions.sql.

create policy profiles_own on public.profiles
  for select to authenticated using (auth_user_id = auth.uid());
create policy profiles_update_own on public.profiles
  for update to authenticated using (auth_user_id = auth.uid()) with check (auth_user_id = auth.uid());

create policy photos_own on public.photos
  for all to authenticated using (user_id = public.me_id()) with check (user_id = public.me_id());

create policy preferences_own on public.preferences
  for all to authenticated using (user_id = public.me_id()) with check (user_id = public.me_id());

create policy privacy_own on public.privacy
  for all to authenticated using (user_id = public.me_id()) with check (user_id = public.me_id());

create policy notification_settings_own on public.notification_settings
  for all to authenticated using (user_id = public.me_id()) with check (user_id = public.me_id());

-- Relationship rows are readable by their participants; writes go through RPCs.
create policy crushes_pair on public.crushes
  for select to authenticated using (from_id = public.me_id() or to_id = public.me_id());

create policy passes_own on public.passes
  for select to authenticated using (from_id = public.me_id());

create policy connections_pair on public.connections
  for select to authenticated using (user_a = public.me_id() or user_b = public.me_id());

create policy conversations_pair on public.conversations
  for select to authenticated using (user_a = public.me_id() or user_b = public.me_id());

create policy messages_pair on public.messages
  for select to authenticated using (
    conversation_id in (
      select id from public.conversations where user_a = public.me_id() or user_b = public.me_id()
    )
  );

create policy message_reactions_pair on public.message_reactions
  for select to authenticated using (
    message_id in (
      select m.id from public.messages m
        join public.conversations c on c.id = m.conversation_id
       where c.user_a = public.me_id() or c.user_b = public.me_id()
    )
  );

-- Moments: the feed itself comes from an RPC; members manage their own moments.
create policy moments_own on public.moments
  for all to authenticated using (user_id = public.me_id()) with check (user_id = public.me_id());

create policy moment_views_own on public.moment_views
  for all to authenticated using (user_id = public.me_id()) with check (user_id = public.me_id());

create policy moment_reactions_own on public.moment_reactions
  for all to authenticated using (user_id = public.me_id()) with check (user_id = public.me_id());

create policy notifications_own on public.notifications
  for all to authenticated using (user_id = public.me_id()) with check (user_id = public.me_id());

create policy blocks_own on public.blocks
  for all to authenticated using (blocker_id = public.me_id()) with check (blocker_id = public.me_id());

create policy reports_insert_own on public.reports
  for insert to authenticated with check (reporter_id = public.me_id());
create policy reports_select_own on public.reports
  for select to authenticated using (reporter_id = public.me_id());

create policy verification_own on public.verification_requests
  for all to authenticated using (user_id = public.me_id()) with check (user_id = public.me_id());

-- ================================ 20261008000002_functions.sql

-- Crushly logic on Supabase: helpers, serializers and RPCs.
--
-- This file is the port of the old Express API (server/src/lib/social.js and
-- server/src/routes/*). Every RPC returns the same JSON shapes the app's
-- `src/api/types.ts` declares, so the client maps 1:1.
--
-- All functions are SECURITY DEFINER so they can see every member's rows (RLS
-- in 0001 keeps raw rows private) and write cross-member side effects
-- (notifications, connections) on the caller's behalf.
--
-- Errors are raised as: message = '__CRUSHLY__<status>__<code>__<message>'
-- which the app's api client turns back into ApiError(status, message, code).
--
-- Convention: RPC parameters are prefixed `p_` so they can never collide with
-- column names inside plpgsql/sql bodies.

-- =====================================================================
--  Internal helpers (not granted to clients)
-- =====================================================================

create or replace function public.age_of(birthdate text) returns integer
language sql immutable as $$
  select case
    when birthdate is null or birthdate !~ '^\d{4}-\d{2}-\d{2}$' then null
    else extract(year from age(current_date, birthdate::date))::integer
  end
$$;

create or replace function public.distance_km(a_lat real, a_lng real, b_lat real, b_lng real)
returns double precision
language sql immutable as $$
  select case
    when a_lat is null or a_lng is null or b_lat is null or b_lng is null then null
    else 2 * 6371 * asin(sqrt(
      power(sin(radians(b_lat - a_lat) / 2), 2) +
      cos(radians(a_lat)) * cos(radians(b_lat)) * power(sin(radians(b_lng - a_lng) / 2), 2)
    ))
  end
$$;

-- Coarse label. Precision deliberately decreases with distance to prevent trilateration.
create or replace function public.distance_label(km double precision) returns text
language sql immutable as $$
  select case
    when km is null then null
    when km < 2 then 'Under 2 km'
    when km < 10 then round(km)::text || ' km'
    when km < 50 then (round(km / 5) * 5)::text || ' km'
    when km < 200 then (round(km / 25) * 25)::text || ' km'
    else 'Far away'
  end
$$;

create or replace function public.is_online_at(last_active bigint) returns boolean
language sql stable as $$
  select public.now_ms() - last_active < 5 * 60 * 1000
$$;

create or replace function public.activity_label_at(last_active bigint) returns text
language sql stable as $$
  select case
    when public.now_ms() - last_active < 5 * 60 * 1000 then 'Online now'
    when public.now_ms() - last_active < 60 * 60 * 1000 then 'Active recently'
    when public.now_ms() - last_active < 24 * 60 * 60 * 1000 then 'Active today'
    when public.now_ms() - last_active < 7 * 24 * 60 * 60 * 1000 then 'Active this week'
    else null
  end
$$;

create or replace function public.is_blocked_pair(a bigint, b bigint) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from blocks
     where (blocker_id = a and blocked_id = b) or (blocker_id = b and blocked_id = a)
  )
$$;

create or replace function public.is_connected_pair(a bigint, b bigint) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from connections where user_a = least(a, b) and user_b = greatest(a, b)
  )
$$;

create or replace function public.connect_pair(a bigint, b bigint) returns void
language sql security definer set search_path = public as $$
  insert into connections (user_a, user_b) values (least(a, b), greatest(a, b))
  on conflict do nothing
$$;

-- Removes the connection and both crushes, and closes any conversation.
create or replace function public.disconnect_pair(a bigint, b bigint) returns void
language sql security definer set search_path = public as $$
  delete from connections where user_a = least(a, b) and user_b = greatest(a, b);
  delete from crushes where (from_id = a and to_id = b) or (from_id = b and to_id = a);
  update conversations set closed = true where user_a = least(a, b) and user_b = greatest(a, b)
$$;

create or replace function public.notification_allowed(p_uid bigint, p_kind text) returns boolean
language sql stable security definer set search_path = public as $$
  select case
    when not exists (select 1 from notification_settings where user_id = p_uid) then true
    when p_kind = 'message' then (select messages from notification_settings where user_id = p_uid)
    when p_kind in ('crush', 'deep_crush', 'mutual') then (select crushes from notification_settings where user_id = p_uid)
    when p_kind in ('moment_reply', 'moment_reaction') then (select moments from notification_settings where user_id = p_uid)
    else true
  end
$$;

create or replace function public.notify_to(
  p_uid bigint, p_kind text, p_actor_id bigint default null, p_ref_id bigint default null, p_body text default ''
) returns void
language plpgsql security definer set search_path = public as $$
declare
  existing_id bigint;
begin
  if not public.notification_allowed(p_uid, p_kind) then
    return;
  end if;
  if p_kind = 'message' and p_actor_id is not null then
    -- Collapse unread message notifications per sender so the center stays calm.
    select nt.id into existing_id from notifications nt
     where nt.user_id = p_uid and nt.kind = 'message' and nt.actor_id = p_actor_id and nt.read_at is null
     limit 1;
    if existing_id is not null then
      update notifications nt
         set created_at = public.now_ms(), body = p_body, ref_id = p_ref_id
       where nt.id = existing_id;
      return;
    end if;
  end if;
  insert into notifications (user_id, kind, actor_id, ref_id, body)
  values (p_uid, p_kind, p_actor_id, p_ref_id, p_body);
end $$;

create or replace function public.photos_of(p_uid bigint) returns jsonb
language sql stable security definer set search_path = public as $$
  select coalesce(jsonb_agg(jsonb_build_object('id', ph.id, 'url', ph.url) order by ph.position, ph.id), '[]'::jsonb)
    from photos ph where ph.user_id = p_uid
$$;

create or replace function public.receipts_visible(a bigint, b bigint) returns boolean
language sql stable security definer set search_path = public as $$
  select count(*) = 2 and bool_and(pr.read_receipts) from privacy pr where pr.user_id in (a, b)
$$;

-- Can `viewer` start/continue a conversation with `target`?
-- Returns null when allowed or a human explanation when not.
create or replace function public.messaging_block_reason(p_viewer bigint, p_target bigint) returns text
language plpgsql stable security definer set search_path = public as $$
declare
  rule text;
  member_name text;
begin
  if p_viewer = p_target then
    return 'You can''t message yourself.';
  end if;
  if public.is_blocked_pair(p_viewer, p_target) then
    return 'This member is no longer available.';
  end if;
  if public.is_connected_pair(p_viewer, p_target) then
    return null;
  end if;
  select coalesce(p.name, 'This member') into member_name from profiles p where p.id = p_target;
  select coalesce(pr.who_can_message, 'mutual') into rule from privacy pr where pr.user_id = p_target;
  if rule = 'everyone' then
    return null;
  end if;
  if rule = 'crushes' and exists (select 1 from crushes c where c.from_id = p_target and c.to_id = p_viewer) then
    return null;
  end if;
  if rule = 'crushes' then
    return member_name || ' only hears from people they''ve crushed on. Send a Crush and see if it''s mutual.';
  end if;
  return member_name || ' only receives messages from Mutual Crushes. Send a Crush first.';
end $$;

-- Serializes a member for another member, applying every privacy rule.
-- Exact coordinates and birthdates never appear in the result.
create or replace function public.public_profile(p_viewer bigint, p_target bigint, p_full boolean default false)
returns jsonb
language plpgsql stable security definer set search_path = public as $$
declare
  r record;
  v record;
  interests jsonb;
  intentions jsonb;
  shared_interests jsonb;
  km double precision;
  my_deep boolean;
  my_note text;
  my_found boolean;
  their_deep boolean;
  their_note text;
  their_found boolean;
  connected boolean;
  can_see_activity boolean;
  result jsonb;
begin
  select p.*, pr.show_distance, pr.show_online, pr.discoverable, pr.profile_visibility,
         pr.who_can_message, pr.who_can_crush, pr.show_age, pr.show_city, pr.incognito
    into r
    from profiles p join privacy pr on pr.user_id = p.id
   where p.id = p_target;
  if not found then
    return null;
  end if;

  select p.lat, p.lng, p.interests, p.intentions, p.verification, pr.show_online
    into v
    from profiles p join privacy pr on pr.user_id = p.id
   where p.id = p_viewer;

  interests := coalesce(r.interests, '[]'::jsonb);
  intentions := coalesce(r.intentions, '[]'::jsonb);
  km := public.distance_km(v.lat, v.lng, r.lat, r.lng);
  connected := public.is_connected_pair(p_viewer, p_target);

  select c.deep, c.note into my_deep, my_note from crushes c
   where c.from_id = p_viewer and c.to_id = p_target;
  my_found := found;
  select c.deep, c.note into their_deep, their_note from crushes c
   where c.from_id = p_target and c.to_id = p_viewer;
  their_found := found;

  can_see_activity := r.show_online and coalesce(v.show_online, true);

  select coalesce(jsonb_agg(i), '[]'::jsonb) into shared_interests
    from jsonb_array_elements_text(interests) i
   where i in (select jsonb_array_elements_text(coalesce(v.interests, '[]'::jsonb)));

  result := jsonb_build_object(
    'id', r.id,
    'name', r.name,
    'age', case when r.show_age then public.age_of(r.birthdate) else null end,
    'pronouns', nullif(r.pronouns, ''),
    'city', case when r.show_city then nullif(r.city, '') else null end,
    'verified', r.verification = 'verified',
    'distance', case when r.show_distance then public.distance_label(km) else null end,
    'online', case when can_see_activity then public.is_online_at(r.last_active_at) else null end,
    'activity', case when can_see_activity then public.activity_label_at(r.last_active_at) else null end,
    'bio', r.bio,
    'intentions', intentions,
    'relationshipIntention', nullif(r.relationship_intention, ''),
    'interests', interests,
    'sharedInterests', shared_interests,
    'photos', public.photos_of(p_target),
    'crush', jsonb_build_object(
      'sent', my_found,
      'sentDeep', coalesce(my_deep, false),
      'received', their_found,
      'receivedDeep', coalesce(their_deep, false),
      'note', case when their_found then their_note else null end,
      'mutual', connected
    ),
    'canMessage', public.messaging_block_reason(p_viewer, p_target) is null,
    'acceptsCrushes', r.who_can_crush <> 'verified' or (v.verification = 'verified')
  );

  if p_full then
    result := result || jsonb_build_object(
      'languages', coalesce(r.languages, '[]'::jsonb),
      'lifestyle', coalesce(r.lifestyle, '{}'::jsonb),
      'messageBlockReason', public.messaging_block_reason(p_viewer, p_target)
    );
  end if;
  return result;
end $$;

-- Loads a member as seen by `viewer`, or null if hidden/blocked/unavailable.
create or replace function public.load_visible_profile(p_viewer bigint, p_target bigint, p_full boolean default false)
returns jsonb
language plpgsql stable security definer set search_path = public as $$
declare
  r record;
begin
  if p_viewer <> p_target and public.is_blocked_pair(p_viewer, p_target) then
    return null;
  end if;
  select p.onboarded, p.status, pr.profile_visibility into r
    from profiles p join privacy pr on pr.user_id = p.id
   where p.id = p_target;
  if not found or not r.onboarded then
    return null;
  end if;
  if p_viewer <> p_target then
    if r.status <> 'active' and not public.is_connected_pair(p_viewer, p_target) then
      return null;
    end if;
    if r.profile_visibility = 'connections'
       and not public.is_connected_pair(p_viewer, p_target)
       and not exists (select 1 from crushes c where c.from_id = p_target and c.to_id = p_viewer) then
      return null;
    end if;
  end if;
  return public.public_profile(p_viewer, p_target, p_full);
end $$;

create or replace function public.peer_summary(p_peer bigint, p_viewer bigint) returns jsonb
language plpgsql stable security definer set search_path = public as $$
declare
  r record;
  my_online boolean;
begin
  select pr.name, pr.verification, pr.last_active_at, pv.show_online
    into r from profiles pr join privacy pv on pv.user_id = pr.id where pr.id = p_peer;
  select pv.show_online into my_online from privacy pv where pv.user_id = p_viewer;
  return jsonb_build_object(
    'id', p_peer,
    'name', coalesce(r.name, 'Member'),
    'verified', r.verification = 'verified',
    'photo', public.photos_of(p_peer) -> 0 ->> 'url',
    'online', case when r.show_online and coalesce(my_online, true)
                   then public.is_online_at(r.last_active_at) else null end
  );
end $$;

create or replace function public.serialize_message(m public.messages, p_viewer bigint, p_show_receipts boolean)
returns jsonb
language sql stable security definer set search_path = public as $$
  select jsonb_build_object(
    'id', m.id,
    'conversationId', m.conversation_id,
    'senderId', m.sender_id,
    'mine', m.sender_id = p_viewer,
    'kind', m.kind,
    'body', m.body,
    'mediaUrl', m.media_url,
    'meta', m.meta,
    'createdAt', m.created_at,
    'readAt', case when m.sender_id = p_viewer and not p_show_receipts then null else m.read_at end,
    'reactions', coalesce((
      select jsonb_agg(jsonb_build_object('userId', r.user_id, 'kind', r.kind))
        from message_reactions r where r.message_id = m.id
    ), '[]'::jsonb)
  )
$$;

create or replace function public.ensure_conversation(a bigint, b bigint) returns bigint
language plpgsql security definer set search_path = public as $$
declare
  conv_id bigint;
begin
  select c.id into conv_id from conversations c
   where c.user_a = least(a, b) and c.user_b = greatest(a, b);
  if conv_id is not null then
    update conversations set closed = false where id = conv_id and closed;
    return conv_id;
  end if;
  insert into conversations (user_a, user_b) values (a, b) returning id into conv_id;
  return conv_id;
end $$;

-- =====================================================================
--  RPCs for the app
-- =====================================================================

create or replace function public.heartbeat() returns void
language sql security definer set search_path = public as $$
  update profiles set last_active_at = public.now_ms() where auth_user_id = auth.uid()
$$;

-- Discover feed. Candidates are filtered by privacy, blocks, prior decisions
-- and the viewer's preferences, then ranked by a light compatibility score.
create or replace function public.discover_feed(p_limit integer default 24, p_offset integer default 0)
returns jsonb
language plpgsql stable security definer set search_path = public as $$
declare
  me bigint := public.me_id();
  v record;
  prefs record;
  scored jsonb := '[]'::jsonb;
  total int := 0;
  items jsonb := '[]'::jsonb;
  r record;
  age int;
  km double precision;
  shared int;
  shared_intent int;
  score numeric;
  overlap boolean;
begin
  if me is null then
    perform public.crushly_fail(401, 'unauthorized', 'Please sign in again.');
  end if;

  select p.lat, p.lng, p.interests, p.intentions into v from profiles p where p.id = me;
  select * into prefs from preferences where user_id = me;

  for r in
    select p.*, pr.show_distance, pr.show_online, pr.discoverable, pr.profile_visibility,
           pr.who_can_message, pr.who_can_crush, pr.show_age, pr.show_city, pr.incognito
      from profiles p join privacy pr on pr.user_id = p.id
     where p.id <> me and p.onboarded and p.status = 'active'
       and pr.discoverable and not pr.incognito and pr.profile_visibility = 'everyone'
       and (not prefs.verified_only or p.verification = 'verified')
       and not public.is_blocked_pair(me, p.id)
       and not exists (select 1 from crushes c where c.from_id = me and c.to_id = p.id)
       and not exists (select 1 from passes x where x.from_id = me and x.to_id = p.id)
       and not public.is_connected_pair(me, p.id)
  loop
    age := public.age_of(r.birthdate);
    if age is null or age < prefs.age_min or age > prefs.age_max then
      continue;
    end if;
    km := public.distance_km(v.lat, v.lng, r.lat, r.lng);
    if prefs.max_distance > 0 and km is not null and km > prefs.max_distance then
      continue;
    end if;

    -- Preference filters require some overlap when set.
    if jsonb_array_length(coalesce(prefs.intentions, '[]'::jsonb)) > 0 then
      select exists (
        select 1 from jsonb_array_elements_text(coalesce(r.intentions, '[]'::jsonb)) i
         where i in (select jsonb_array_elements_text(coalesce(prefs.intentions, '[]'::jsonb)))
      ) into overlap;
      if not overlap then continue; end if;
    end if;
    if jsonb_array_length(coalesce(prefs.interests, '[]'::jsonb)) > 0 then
      select exists (
        select 1 from jsonb_array_elements_text(coalesce(r.interests, '[]'::jsonb)) i
         where i in (select jsonb_array_elements_text(coalesce(prefs.interests, '[]'::jsonb)))
      ) into overlap;
      if not overlap then continue; end if;
    end if;

    select count(*)::int into shared from jsonb_array_elements_text(coalesce(r.interests, '[]'::jsonb)) i
     where i in (select jsonb_array_elements_text(coalesce(v.interests, '[]'::jsonb)));
    select count(*)::int into shared_intent from jsonb_array_elements_text(coalesce(r.intentions, '[]'::jsonb)) i
     where i in (select jsonb_array_elements_text(coalesce(v.intentions, '[]'::jsonb)));

    score := shared * 3 + shared_intent * 2;
    if r.verification = 'verified' then score := score + 2; end if;
    if public.is_online_at(r.last_active_at) then score := score + 3; end if;
    if km is not null then score := score + greatest(0, 4 - km / 10); end if;
    if exists (select 1 from crushes c where c.from_id = r.id and c.to_id = me) then
      score := score + 1; -- gently surface people already into you
    end if;

    scored := scored || jsonb_build_array(jsonb_build_object(
      'id', r.id, 'score', score, 'last', r.last_active_at,
      'profile', public.public_profile(me, r.id, false)
    ));
  end loop;

  total := jsonb_array_length(scored);

  with ordered as (
    select value as item, row_number() over (
      order by (value ->> 'score')::numeric desc, (value ->> 'last')::bigint desc
    ) as rn
      from jsonb_array_elements(scored)
  )
  select coalesce(jsonb_agg(item -> 'profile' order by rn), '[]'::jsonb) into items
    from ordered where rn > p_offset and rn <= p_offset + greatest(coalesce(p_limit, 24), 1);

  return jsonb_build_object(
    'items', items,
    'nextOffset', case
      when p_offset + greatest(coalesce(p_limit, 24), 1) < total
        then p_offset + greatest(coalesce(p_limit, 24), 1)
      else null end,
    'total', total,
    'viewerHasLocation', v.lat is not null
  );
end $$;

create or replace function public.load_profile(p_target_id bigint) returns jsonb
language plpgsql stable security definer set search_path = public as $$
declare
  me bigint := public.me_id();
  profile jsonb;
begin
  if me is null then
    perform public.crushly_fail(401, 'unauthorized', 'Please sign in again.');
  end if;
  profile := public.load_visible_profile(me, p_target_id, true);
  if profile is null then
    return null;
  end if;
  return profile || jsonb_build_object(
    'moments', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', t.id, 'kind', t.kind, 'body', t.body, 'mediaUrl', t.media_url,
        'style', t.style, 'createdAt', t.created_at
      ) order by t.id desc)
        from (
          select id, kind, body, media_url, style, created_at
            from moments
           where user_id = p_target_id and expires_at > public.now_ms()
             and (audience = 'everyone' or public.is_connected_pair(me, p_target_id))
           order by id desc limit 6
        ) t
    ), '[]'::jsonb)
  );
end $$;

-- Crush (or Deep Crush). Returns { mutual: true } when the feeling is mutual,
-- at which point a connection is created and both members are notified.
create or replace function public.crush_member(p_target_id bigint, p_is_deep boolean default false, p_note text default null)
returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  me bigint := public.me_id();
  target record;
  existing boolean;
  existing_found boolean;
  reciprocal boolean;
  already_connected boolean;
  used int;
  mutual_now boolean := false;
  is_new boolean := false;
  clean_note text;
begin
  if me is null then
    perform public.crushly_fail(401, 'unauthorized', 'Please sign in again.');
  end if;
  if me = p_target_id then
    perform public.crushly_fail(400, '', 'You can’t crush on yourself — though we admire the confidence.');
  end if;
  if public.load_visible_profile(me, p_target_id) is null then
    perform public.crushly_fail(404, '', 'This profile isn’t available.');
  end if;
  select pf.name, pv.who_can_crush into target from profiles pf
    join privacy pv on pv.user_id = pf.id where pf.id = p_target_id;
  if target.who_can_crush = 'verified'
     and not exists (select 1 from profiles pf where pf.id = me and pf.verification = 'verified') then
    perform public.crushly_fail(403, 'verification_required',
      target.name || ' only accepts Crushes from verified members.');
  end if;

  clean_note := case when p_note is null or btrim(p_note) = '' then null else left(btrim(p_note), 140) end;

  select c.deep into existing from crushes c where c.from_id = me and c.to_id = p_target_id;
  existing_found := found;
  if p_is_deep and not coalesce(existing, false) then
    select count(*)::int into used from crushes c
     where c.from_id = me and c.deep and c.created_at > public.now_ms() - 24 * 60 * 60 * 1000;
    if used >= 3 then
      perform public.crushly_fail(429, 'deep_limit',
        'You’ve sent your 3 Deep Crushes for today. They refresh tomorrow — a regular Crush still says plenty.');
    end if;
  end if;

  insert into crushes (from_id, to_id, deep, note, created_at)
  values (me, p_target_id, coalesce(p_is_deep, false), clean_note, public.now_ms())
  on conflict (from_id, to_id) do update
    set deep = crushes.deep or excluded.deep,
        note = coalesce(excluded.note, crushes.note);
  delete from passes where from_id = me and to_id = p_target_id;

  reciprocal := exists (select 1 from crushes c where c.from_id = p_target_id and c.to_id = me);
  already_connected := public.is_connected_pair(me, p_target_id);

  if reciprocal and not already_connected then
    perform public.connect_pair(me, p_target_id);
    perform public.notify_to(p_target_id, 'mutual', me, null, '');
    perform public.notify_to(me, 'mutual', p_target_id, null, '');
    mutual_now := true;
    is_new := true;
  else
    if not existing_found or (coalesce(p_is_deep, false) and not coalesce(existing, false)) then
      perform public.notify_to(p_target_id, case when coalesce(p_is_deep, false) then 'deep_crush' else 'crush' end,
                       me, null, coalesce(clean_note, ''));
    end if;
    mutual_now := already_connected;
    is_new := false;
  end if;

  return jsonb_build_object(
    'mutual', mutual_now,
    'isNew', is_new,
    'profile', public.load_visible_profile(me, p_target_id)
  );
end $$;

create or replace function public.uncrush_member(p_target_id bigint) returns boolean
language plpgsql security definer set search_path = public as $$
declare
  me bigint := public.me_id();
begin
  if me is null then
    perform public.crushly_fail(401, 'unauthorized', 'Please sign in again.');
  end if;
  if public.is_connected_pair(me, p_target_id) then
    perform public.crushly_fail(400, '', 'You’re already connected. Use “Remove connection” to end it.');
  end if;
  delete from crushes where from_id = me and to_id = p_target_id;
  return true;
end $$;

create or replace function public.pass_member(p_target_id bigint) returns boolean
language plpgsql security definer set search_path = public as $$
declare
  me bigint := public.me_id();
begin
  if me is null then
    perform public.crushly_fail(401, 'unauthorized', 'Please sign in again.');
  end if;
  insert into passes (from_id, to_id) values (me, p_target_id)
  on conflict (from_id, to_id) do update set created_at = public.now_ms();
  return true;
end $$;

-- Crushes hub: who's crushing on you, your crushes, and Mutual Crushes.
create or replace function public.crushes_feed() returns jsonb
language plpgsql stable security definer set search_path = public as $$
declare
  me bigint := public.me_id();
  incoming jsonb;
  outgoing jsonb;
  mutual jsonb;
begin
  if me is null then
    perform public.crushly_fail(401, 'unauthorized', 'Please sign in again.');
  end if;

  with src as (
    select c.created_at as at, p.id as pid,
           row_number() over (order by c.deep desc, c.created_at desc) as rn
      from crushes c join profiles p on p.id = c.from_id
     where c.to_id = me
       and not public.is_connected_pair(me, p.id)
       and not exists (select 1 from passes x where x.from_id = me and x.to_id = p.id)
       and not public.is_blocked_pair(me, p.id)
       and p.onboarded and p.status = 'active'
  )
  select coalesce(jsonb_agg(public.public_profile(me, src.pid, false) || jsonb_build_object('at', src.at)
                            order by src.rn), '[]'::jsonb)
    into incoming from src;

  with src as (
    select c.created_at as at, p.id as pid,
           row_number() over (order by c.created_at desc) as rn
      from crushes c join profiles p on p.id = c.to_id
     where c.from_id = me
       and not public.is_connected_pair(me, p.id)
       and not public.is_blocked_pair(me, p.id)
       and p.onboarded and p.status = 'active'
  )
  select coalesce(jsonb_agg(public.public_profile(me, src.pid, false) || jsonb_build_object('at', src.at)
                            order by src.rn), '[]'::jsonb)
    into outgoing from src;

  with src as (
    select k.created_at as at,
           case when k.user_a = me then k.user_b else k.user_a end as pid,
           row_number() over (order by k.created_at desc) as rn
      from connections k
     where k.user_a = me or k.user_b = me
  )
  select coalesce(jsonb_agg(public.public_profile(me, src.pid, false) || jsonb_build_object('at', src.at)
                            order by src.rn), '[]'::jsonb)
    into mutual from src
   where not public.is_blocked_pair(me, src.pid)
     and exists (select 1 from profiles p where p.id = src.pid and p.onboarded and p.status = 'active');

  return jsonb_build_object('incoming', incoming, 'outgoing', outgoing, 'mutual', mutual);
end $$;

-- Remove connection (unmatch). Ends the Mutual Crush and closes the conversation for both.
create or replace function public.remove_connection(p_target_id bigint) returns boolean
language plpgsql security definer set search_path = public as $$
declare
  me bigint := public.me_id();
begin
  if me is null then
    perform public.crushly_fail(401, 'unauthorized', 'Please sign in again.');
  end if;
  perform public.disconnect_pair(me, p_target_id);
  insert into passes (from_id, to_id) values (me, p_target_id)
  on conflict (from_id, to_id) do update set created_at = public.now_ms();
  return true;
end $$;

create or replace function public.block_member(p_target_id bigint) returns boolean
language plpgsql security definer set search_path = public as $$
declare
  me bigint := public.me_id();
begin
  if me is null then
    perform public.crushly_fail(401, 'unauthorized', 'Please sign in again.');
  end if;
  if me = p_target_id then
    perform public.crushly_fail(400, '', 'You can’t block yourself.');
  end if;
  if not exists (select 1 from profiles p where p.id = p_target_id) then
    perform public.crushly_fail(404, '', 'Member not found.');
  end if;
  insert into blocks (blocker_id, blocked_id) values (me, p_target_id) on conflict do nothing;
  perform public.disconnect_pair(me, p_target_id);
  return true;
end $$;

create or replace function public.unblock_member(p_target_id bigint) returns boolean
language sql security definer set search_path = public as $$
  delete from blocks where blocker_id = public.me_id() and blocked_id = p_target_id;
  select true
$$;

create or replace function public.report_member(
  p_target_id bigint, p_reason text, p_details text default '', p_context text default '', p_also_block boolean default false
) returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  me bigint := public.me_id();
begin
  if me is null then
    perform public.crushly_fail(401, 'unauthorized', 'Please sign in again.');
  end if;
  if me = p_target_id then
    perform public.crushly_fail(400, '', 'You can’t report yourself.');
  end if;
  if not exists (select 1 from profiles p where p.id = p_target_id) then
    perform public.crushly_fail(404, '', 'Member not found.');
  end if;
  if p_reason not in ('fake_profile', 'harassment', 'inappropriate_content', 'scam',
                      'underage', 'hate_speech', 'threats_safety', 'other') then
    perform public.crushly_fail(400, '', 'Choose a reason so we know how to help.');
  end if;
  if char_length(coalesce(p_details, '')) > 1000 or char_length(coalesce(p_context, '')) > 60 then
    perform public.crushly_fail(400, '', 'Please keep reports short and specific.');
  end if;
  insert into reports (reporter_id, reported_id, reason, details, context)
  values (me, p_target_id, p_reason, left(coalesce(p_details, ''), 1000), left(coalesce(p_context, ''), 60));
  if coalesce(p_also_block, false) then
    insert into blocks (blocker_id, blocked_id) values (me, p_target_id) on conflict do nothing;
    perform public.disconnect_pair(me, p_target_id);
  end if;
  return jsonb_build_object('ok', true, 'blocked', coalesce(p_also_block, false));
end $$;

-- Opens (or reopens) a conversation with a member, if their privacy settings allow it.
create or replace function public.open_conversation(p_target_id bigint) returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  me bigint := public.me_id();
  reason text;
  conv_id bigint;
begin
  if me is null then
    perform public.crushly_fail(401, 'unauthorized', 'Please sign in again.');
  end if;
  if p_target_id is null or p_target_id <= 0 then
    perform public.crushly_fail(400, '', 'Who would you like to message?');
  end if;
  reason := public.messaging_block_reason(me, p_target_id);
  if reason is not null then
    perform public.crushly_fail(403, 'messaging_restricted', reason);
  end if;
  if public.load_visible_profile(me, p_target_id) is null then
    perform public.crushly_fail(404, '', 'This profile isn’t available.');
  end if;
  conv_id := public.ensure_conversation(me, p_target_id);
  return jsonb_build_object('id', conv_id, 'peer', public.peer_summary(p_target_id, me));
end $$;

create or replace function public.load_conversation(p_conversation_id bigint) returns jsonb
language plpgsql stable security definer set search_path = public as $$
declare
  me bigint := public.me_id();
  conv record;
  peer bigint;
  reason text;
begin
  if me is null then
    perform public.crushly_fail(401, 'unauthorized', 'Please sign in again.');
  end if;
  select * into conv from conversations c where c.id = p_conversation_id;
  if not found or (conv.user_a <> me and conv.user_b <> me) then
    perform public.crushly_fail(404, '', 'Conversation not found.');
  end if;
  peer := case when conv.user_a = me then conv.user_b else conv.user_a end;
  if public.is_blocked_pair(me, peer) then
    perform public.crushly_fail(404, '', 'Conversation not found.');
  end if;
  reason := public.messaging_block_reason(me, peer);
  return jsonb_build_object(
    'id', conv.id,
    'closed', conv.closed,
    'peer', public.peer_summary(peer, me),
    'canSend', not conv.closed and reason is null,
    'blockReason', case when conv.closed then 'This connection has ended.' else reason end
  );
end $$;

create or replace function public.list_conversations() returns jsonb
language plpgsql stable security definer set search_path = public as $$
declare
  me bigint := public.me_id();
  items jsonb;
begin
  if me is null then
    perform public.crushly_fail(401, 'unauthorized', 'Please sign in again.');
  end if;
  select coalesce(jsonb_agg(jsonb_build_object(
    'id', c.id,
    'peer', public.peer_summary(case when c.user_a = me then c.user_b else c.user_a end, me),
    'lastMessage', (
      select public.serialize_message(m, me, false) from messages m
       where m.conversation_id = c.id order by m.id desc limit 1
    ),
    'unread', (
      select count(*)::int from messages m
       where m.conversation_id = c.id and m.sender_id <> me and m.read_at is null
    ),
    'updatedAt', coalesce(c.last_message_at, c.created_at)
  ) order by coalesce(c.last_message_at, c.created_at) desc), '[]'::jsonb)
  into items
  from conversations c
  where (c.user_a = me or c.user_b = me) and not c.closed
    and not public.is_blocked_pair(me, case when c.user_a = me then c.user_b else c.user_a end);

  return jsonb_build_object('items', items);
end $$;

-- Paged history. `after` fetches newer messages (polling); `before` pages back.
create or replace function public.get_messages(
  p_conversation_id bigint, p_after_id bigint default 0, p_before_id bigint default 0, p_limit integer default 40
) returns jsonb
language plpgsql stable security definer set search_path = public as $$
declare
  me bigint := public.me_id();
  conv record;
  peer bigint;
  show_receipts boolean;
  lim integer := least(greatest(coalesce(p_limit, 40), 1), 100);
  items jsonb;
  has_more boolean := false;
  last_read_mine bigint;
begin
  if me is null then
    perform public.crushly_fail(401, 'unauthorized', 'Please sign in again.');
  end if;
  select * into conv from conversations c where c.id = p_conversation_id;
  if not found or (conv.user_a <> me and conv.user_b <> me) then
    perform public.crushly_fail(404, '', 'Conversation not found.');
  end if;
  peer := case when conv.user_a = me then conv.user_b else conv.user_a end;
  if public.is_blocked_pair(me, peer) then
    perform public.crushly_fail(404, '', 'Conversation not found.');
  end if;
  show_receipts := public.receipts_visible(me, peer);

  if coalesce(p_after_id, 0) > 0 then
    select coalesce(jsonb_agg(public.serialize_message(m, me, show_receipts) order by m.id), '[]'::jsonb) into items
      from (select * from messages ms where ms.conversation_id = p_conversation_id and ms.id > p_after_id
            order by ms.id asc limit lim) m;
    has_more := false;
  elsif coalesce(p_before_id, 0) > 0 then
    select coalesce(jsonb_agg(public.serialize_message(m, me, show_receipts) order by m.id), '[]'::jsonb) into items
      from (select * from messages ms where ms.conversation_id = p_conversation_id and ms.id < p_before_id
            order by ms.id desc limit lim) m;
    has_more := jsonb_array_length(items) = lim;
  else
    select coalesce(jsonb_agg(public.serialize_message(m, me, show_receipts) order by m.id), '[]'::jsonb) into items
      from (select * from messages ms where ms.conversation_id = p_conversation_id
            order by ms.id desc limit lim) m;
    has_more := jsonb_array_length(items) = lim;
  end if;

  if show_receipts then
    select max(ms.id) into last_read_mine from messages ms
     where ms.conversation_id = p_conversation_id and ms.sender_id = me and ms.read_at is not null;
  end if;

  return jsonb_build_object('items', items, 'hasMore', has_more, 'lastReadMine', last_read_mine);
end $$;

create or replace function public.send_message(
  p_conversation_id bigint, p_kind text default 'text', p_body text default '',
  p_media_url text default null, p_meta jsonb default '{}'
) returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  me bigint := public.me_id();
  conv record;
  peer bigint;
  reason text;
  new_id bigint;
  clean_body text := coalesce(p_body, '');
  clean_meta jsonb := coalesce(p_meta, '{}'::jsonb);
  clean_media text := nullif(coalesce(p_media_url, ''), '');
  shared jsonb;
  preview text;
begin
  if me is null then
    perform public.crushly_fail(401, 'unauthorized', 'Please sign in again.');
  end if;
  select * into conv from conversations c where c.id = p_conversation_id;
  if not found or (conv.user_a <> me and conv.user_b <> me) then
    perform public.crushly_fail(404, '', 'Conversation not found.');
  end if;
  peer := case when conv.user_a = me then conv.user_b else conv.user_a end;
  if conv.closed then
    perform public.crushly_fail(403, '', 'This connection has ended.');
  end if;
  reason := public.messaging_block_reason(me, peer);
  if reason is not null then
    perform public.crushly_fail(403, 'messaging_restricted', reason);
  end if;

  case p_kind
    when 'text' then
      if btrim(clean_body) = '' then
        perform public.crushly_fail(400, '', 'Say something worth replying to.');
      end if;
      clean_body := left(clean_body, 2000);
    when 'photo' then
      if clean_media is null then
        perform public.crushly_fail(400, '', 'Choose a photo to send.');
      end if;
      clean_body := left(clean_body, 300);
    when 'voice' then
      if clean_media is null then
        perform public.crushly_fail(400, '', 'Record a voice message to send.');
      end if;
      clean_meta := jsonb_build_object('duration',
        least(greatest(coalesce((clean_meta ->> 'duration')::int, 1), 1), 300));
    when 'sticker' then
      if clean_meta ->> 'sticker' not in ('wave', 'blush', 'fire', 'cheers', 'wink', 'heart_eyes', 'coffee', 'crown') then
        perform public.crushly_fail(400, '', 'Pick a sticker to send.');
      end if;
    when 'profile' then
      shared := public.load_visible_profile(me, (clean_meta ->> 'profileId')::bigint);
      if shared is null then
        perform public.crushly_fail(404, '', 'That profile can’t be shared.');
      end if;
      clean_meta := jsonb_build_object(
        'profileId', (shared ->> 'id')::bigint,
        'name', shared ->> 'name',
        'age', shared -> 'age',
        'photo', shared #>> '{photos,0,url}',
        'verified', (shared ->> 'verified')::boolean);
    else
      perform public.crushly_fail(400, '', 'Unsupported message type.');
  end case;

  insert into messages (conversation_id, sender_id, kind, body, media_url, meta)
  values (p_conversation_id, me, p_kind, clean_body, clean_media, clean_meta)
  returning id into new_id;
  update conversations set last_message_at = public.now_ms() where id = p_conversation_id;

  preview := case p_kind
    when 'text' then left(clean_body, 80)
    when 'photo' then 'Sent a photo'
    when 'voice' then 'Sent a voice message'
    when 'sticker' then 'Sent a sticker'
    else 'Shared a profile'
  end;
  perform public.notify_to(peer, 'message', me, p_conversation_id, preview);

  return (
    select public.serialize_message(m, me, public.receipts_visible(me, peer))
      from messages m where m.id = new_id
  );
end $$;

create or replace function public.mark_conversation_read(p_conversation_id bigint) returns boolean
language plpgsql security definer set search_path = public as $$
declare
  me bigint := public.me_id();
  conv record;
begin
  if me is null then
    perform public.crushly_fail(401, 'unauthorized', 'Please sign in again.');
  end if;
  select * into conv from conversations c where c.id = p_conversation_id;
  if not found or (conv.user_a <> me and conv.user_b <> me) then
    perform public.crushly_fail(404, '', 'Conversation not found.');
  end if;
  update messages ms set read_at = public.now_ms()
   where ms.conversation_id = p_conversation_id and ms.sender_id <> me and ms.read_at is null;
  update notifications nt set read_at = public.now_ms()
   where nt.user_id = me and nt.kind = 'message' and nt.ref_id = p_conversation_id and nt.read_at is null;
  return true;
end $$;

-- Crush reaction on a message (toggle).
create or replace function public.toggle_message_reaction(p_message_id bigint, p_kind text default 'crush')
returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  me bigint := public.me_id();
  msg record;
  conv record;
  existing_kind text;
  peer bigint;
begin
  if me is null then
    perform public.crushly_fail(401, 'unauthorized', 'Please sign in again.');
  end if;
  select * into msg from messages ms where ms.id = p_message_id;
  if not found then
    perform public.crushly_fail(404, '', 'Message not found.');
  end if;
  select * into conv from conversations c where c.id = msg.conversation_id;
  if conv.user_a <> me and conv.user_b <> me then
    perform public.crushly_fail(404, '', 'Conversation not found.');
  end if;
  peer := case when conv.user_a = me then conv.user_b else conv.user_a end;
  if coalesce(p_kind, 'crush') not in ('crush', 'laugh', 'fire', 'wow') then
    p_kind := 'crush';
  end if;
  select r.kind into existing_kind from message_reactions r
   where r.message_id = msg.id and r.user_id = me;
  if existing_kind = p_kind then
    delete from message_reactions r where r.message_id = msg.id and r.user_id = me;
  else
    insert into message_reactions (message_id, user_id, kind) values (msg.id, me, p_kind)
    on conflict (message_id, user_id) do update set kind = excluded.kind, created_at = public.now_ms();
  end if;
  return (
    select public.serialize_message(m, me, public.receipts_visible(me, peer))
      from messages m where m.id = msg.id
  );
end $$;

-- ---------------------------------------------------------------- moments

create or replace function public.serialize_moment(m public.moments, p_viewer bigint) returns jsonb
language plpgsql stable security definer set search_path = public as $$
declare
  mine boolean := m.user_id = p_viewer;
  result jsonb;
begin
  result := jsonb_build_object(
    'id', m.id,
    'userId', m.user_id,
    'kind', m.kind,
    'body', m.body,
    'mediaUrl', m.media_url,
    'style', m.style,
    'audience', m.audience,
    'createdAt', m.created_at,
    'expiresAt', m.expires_at,
    'seen', exists (select 1 from moment_views mv where mv.moment_id = m.id and mv.user_id = p_viewer),
    'myReaction', (select r.kind from moment_reactions r where r.moment_id = m.id and r.user_id = p_viewer),
    -- Author card for the feed's grouping (the app strips it into MomentAuthor).
    'author', (
      select jsonb_build_object(
        'id', pf.id,
        'name', pf.name,
        'verified', pf.verification = 'verified',
        'photo', public.photos_of(pf.id) -> 0 ->> 'url',
        'mutual', pf.id <> p_viewer and public.is_connected_pair(p_viewer, pf.id)
      ) from profiles pf where pf.id = m.user_id
    )
  );
  if mine then
    result := result || jsonb_build_object(
      'viewCount', (select count(*)::int from moment_views mv where mv.moment_id = m.id and mv.user_id <> p_viewer),
      'reactions', coalesce((
        select jsonb_agg(jsonb_build_object('kind', r.kind, 'userId', r.user_id, 'name', p.name)
                         order by r.created_at desc)
          from moment_reactions r join profiles p on p.id = r.user_id
         where r.moment_id = m.id
      ), '[]'::jsonb)
    );
  end if;
  return result;
end $$;

create or replace function public.can_view_moment(m public.moments, p_viewer bigint) returns boolean
language plpgsql stable security definer set search_path = public as $$
declare
  owner record;
begin
  if m.user_id = p_viewer then return true; end if;
  if m.expires_at <= public.now_ms() then return false; end if;
  if public.is_blocked_pair(p_viewer, m.user_id) then return false; end if;
  if m.audience = 'connections' and not public.is_connected_pair(p_viewer, m.user_id) then return false; end if;
  select p.status, p.onboarded, pr.profile_visibility into owner
    from profiles p join privacy pr on pr.user_id = p.id where p.id = m.user_id;
  if not found or owner.status <> 'active' or not owner.onboarded then return false; end if;
  if owner.profile_visibility = 'connections'
     and not public.is_connected_pair(p_viewer, m.user_id) then return false; end if;
  return true;
end $$;

-- Feed as a flat, serialized list. The app groups by member (yours first, then
-- unseen, Mutual Crushes before everyone else).
create or replace function public.visible_moments() returns setof jsonb
language plpgsql stable security definer set search_path = public as $$
declare
  me bigint := public.me_id();
  m public.moments;
begin
  if me is null then
    perform public.crushly_fail(401, 'unauthorized', 'Please sign in again.');
  end if;
  for m in select * from moments mo where mo.expires_at > public.now_ms() order by mo.created_at asc loop
    if public.can_view_moment(m, me) then
      return next public.serialize_moment(m, me);
    end if;
  end loop;
end $$;

create or replace function public.create_moment(
  p_kind text default 'text', p_body text default '', p_media_url text default null,
  p_style text default 'noir', p_audience text default 'everyone'
) returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  me bigint := public.me_id();
  clean_kind text := coalesce(p_kind, 'text');
  clean_body text := coalesce(p_body, '');
  clean_style text := coalesce(p_style, 'noir');
  clean_audience text := coalesce(p_audience, 'everyone');
  new_id bigint;
  m public.moments;
begin
  if me is null then
    perform public.crushly_fail(401, 'unauthorized', 'Please sign in again.');
  end if;
  if clean_kind not in ('text', 'photo') then
    perform public.crushly_fail(400, '', 'Moments are words or a photo.');
  end if;
  if clean_style not in ('noir', 'champagne', 'crimson', 'midnight', 'emerald') then
    clean_style := 'noir';
  end if;
  if clean_audience not in ('everyone', 'connections') then
    clean_audience := 'everyone';
  end if;
  if clean_kind = 'text' and btrim(clean_body) = '' then
    perform public.crushly_fail(400, '', 'Say something in your Moment.');
  end if;
  clean_body := left(clean_body, case when clean_kind = 'text' then 280 else 200 end);

  insert into moments (user_id, kind, body, media_url, style, audience, expires_at)
  values (me, clean_kind, clean_body, nullif(coalesce(p_media_url, ''), ''), clean_style, clean_audience,
          public.now_ms() + 24 * 60 * 60 * 1000)
  returning id into new_id;
  select * into m from moments mo where mo.id = new_id;
  return public.serialize_moment(m, me);
end $$;

create or replace function public.delete_moment(p_moment_id bigint) returns boolean
language plpgsql security definer set search_path = public as $$
declare
  me bigint := public.me_id();
  m public.moments;
begin
  select * into m from moments mo where mo.id = p_moment_id and mo.user_id = me;
  if not found then
    perform public.crushly_fail(404, '', 'Moment not found.');
  end if;
  delete from moments mo where mo.id = m.id;
  return true;
end $$;

create or replace function public.view_moment(p_moment_id bigint) returns boolean
language plpgsql security definer set search_path = public as $$
declare
  me bigint := public.me_id();
  m public.moments;
begin
  select * into m from moments mo where mo.id = p_moment_id;
  if not found or not public.can_view_moment(m, me) then
    perform public.crushly_fail(404, '', 'This Moment has passed.');
  end if;
  if m.user_id <> me then
    insert into moment_views (moment_id, user_id) values (m.id, me)
    on conflict do nothing;
  end if;
  return true;
end $$;

create or replace function public.react_to_moment(p_moment_id bigint, p_kind text default null) returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  me bigint := public.me_id();
  m public.moments;
  had boolean;
begin
  select * into m from moments mo where mo.id = p_moment_id;
  if not found or not public.can_view_moment(m, me) then
    perform public.crushly_fail(404, '', 'This Moment has passed.');
  end if;
  if m.user_id = me then
    perform public.crushly_fail(400, '', 'You can’t react to your own Moment.');
  end if;
  if p_kind is not null and p_kind not in ('crush', 'fire', 'laugh', 'wow', 'clap') then
    perform public.crushly_fail(400, '', 'That reaction doesn’t exist.');
  end if;
  select exists (select 1 from moment_reactions r where r.moment_id = m.id and r.user_id = me) into had;
  if p_kind is null then
    delete from moment_reactions r where r.moment_id = m.id and r.user_id = me;
  else
    insert into moment_reactions (moment_id, user_id, kind) values (m.id, me, p_kind)
    on conflict (moment_id, user_id) do update set kind = excluded.kind, created_at = public.now_ms();
    if not had then
      perform public.notify_to(m.user_id, 'moment_reaction', me, m.id, p_kind);
    end if;
  end if;
  return (
    select public.serialize_moment(x, me) from moments x where x.id = m.id
  );
end $$;

-- Replying to a Moment sends a private message that quotes it.
create or replace function public.reply_to_moment(p_moment_id bigint, p_body text) returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  me bigint := public.me_id();
  m public.moments;
  reason text;
  conv_id bigint;
  clean_body text := coalesce(p_body, '');
begin
  select * into m from moments mo where mo.id = p_moment_id;
  if not found or not public.can_view_moment(m, me) then
    perform public.crushly_fail(404, '', 'This Moment has passed.');
  end if;
  if m.user_id = me then
    perform public.crushly_fail(400, '', 'You can’t reply to your own Moment.');
  end if;
  if btrim(clean_body) = '' then
    perform public.crushly_fail(400, '', 'Write a reply first.');
  end if;
  clean_body := left(clean_body, 1000);
  reason := public.messaging_block_reason(me, m.user_id);
  if reason is not null then
    perform public.crushly_fail(403, 'messaging_restricted', reason);
  end if;
  conv_id := public.ensure_conversation(me, m.user_id);
  insert into messages (conversation_id, sender_id, kind, body, meta)
  values (conv_id, me, 'moment_reply', clean_body, jsonb_build_object(
    'momentId', m.id, 'momentKind', m.kind, 'momentBody', left(m.body, 120),
    'momentMedia', m.media_url, 'momentStyle', m.style));
  update conversations set last_message_at = public.now_ms() where id = conv_id;
  perform public.notify_to(m.user_id, 'moment_reply', me, conv_id, left(clean_body, 80));
  return jsonb_build_object('conversationId', conv_id);
end $$;

-- ---------------------------------------------------------- notifications

create or replace function public.list_notifications() returns setof jsonb
language plpgsql stable security definer set search_path = public as $$
declare
  me bigint := public.me_id();
  n record;
begin
  if me is null then
    perform public.crushly_fail(401, 'unauthorized', 'Please sign in again.');
  end if;
  for n in
    select nt.*, pf.name as actor_name, pf.verification as actor_verification
      from notifications nt left join profiles pf on pf.id = nt.actor_id
     where nt.user_id = me
     order by nt.created_at desc, nt.id desc
     limit 100
  loop
    if n.actor_id is not null and public.is_blocked_pair(me, n.actor_id) then
      continue;
    end if;
    return next jsonb_build_object(
      'id', n.id,
      'kind', n.kind,
      'body', n.body,
      'refId', n.ref_id,
      'createdAt', n.created_at,
      'read', n.read_at is not null,
      'actor', case when n.actor_id is null then null else jsonb_build_object(
        'id', n.actor_id,
        'name', n.actor_name,
        'verified', n.actor_verification = 'verified',
        'photo', public.photos_of(n.actor_id) -> 0 ->> 'url'
      ) end
    );
  end loop;
end $$;

create or replace function public.badges() returns jsonb
language plpgsql stable security definer set search_path = public as $$
declare
  me bigint := public.me_id();
  latest record;
begin
  if me is null then
    perform public.crushly_fail(401, 'unauthorized', 'Please sign in again.');
  end if;
  select n.id, n.kind, n.body, n.actor_id, pf.name as actor_name
    into latest
    from notifications n left join profiles pf on pf.id = n.actor_id
   where n.user_id = me
   order by n.id desc limit 1;

  return jsonb_build_object(
    'notifications', (select count(*)::int from notifications n where n.user_id = me and n.read_at is null),
    'messages', (
      select count(*)::int
        from messages m join conversations c on c.id = m.conversation_id
       where (c.user_a = me or c.user_b = me) and not c.closed
         and m.sender_id <> me and m.read_at is null
         and not public.is_blocked_pair(me, m.sender_id)
    ),
    'crushes', (
      select count(*)::int from notifications n
       where n.user_id = me and n.read_at is null and n.kind in ('crush', 'deep_crush', 'mutual')
    ),
    'latestNotification', case when latest.id is null then null else jsonb_build_object(
      'id', latest.id, 'kind', latest.kind, 'body', latest.body,
      'actor_id', latest.actor_id, 'actor_name', latest.actor_name) end
  );
end $$;

-- The members you blocked (names and photos are not readable under RLS).
create or replace function public.list_blocks() returns setof jsonb
language sql stable security definer set search_path = public as $$
  select jsonb_build_object(
    'id', b.blocked_id,
    'name', pf.name,
    'photo', public.photos_of(b.blocked_id) -> 0 ->> 'url',
    'blockedAt', b.created_at
  )
  from blocks b join profiles pf on pf.id = b.blocked_id
  where b.blocker_id = public.me_id()
  order by b.created_at desc
$$;

-- ------------------------------------------------------------- account

-- Verifies the password, then deletes the auth user. Profiles and everything
-- else cascade away (see the FK chain in 0001).
create or replace function public.delete_account(p_password text) returns boolean
language plpgsql security definer set search_path = public, extensions as $$
declare
  me uuid := auth.uid();
  encrypted text;
begin
  if me is null then
    perform public.crushly_fail(401, 'unauthorized', 'Please sign in again.');
  end if;
  select u.encrypted_password into encrypted from auth.users u where u.id = me;
  if encrypted is null or extensions.crypt(coalesce(p_password, ''), encrypted) <> encrypted then
    perform public.crushly_fail(403, '', 'Enter your password to delete your account.');
  end if;
  delete from auth.users u where u.id = me;
  return true;
end $$;

-- =====================================================================
--  Grants: RPCs run for signed-in members only; helpers stay private.
-- =====================================================================

do $$
declare
  fn text;
begin
  foreach fn in array array[
    'heartbeat()',
    'discover_feed(integer,integer)',
    'load_profile(bigint)',
    'crush_member(bigint,boolean,text)',
    'uncrush_member(bigint)',
    'pass_member(bigint)',
    'crushes_feed()',
    'remove_connection(bigint)',
    'block_member(bigint)',
    'unblock_member(bigint)',
    'report_member(bigint,text,text,text,boolean)',
    'open_conversation(bigint)',
    'load_conversation(bigint)',
    'list_conversations()',
    'get_messages(bigint,bigint,bigint,integer)',
    'send_message(bigint,text,text,text,jsonb)',
    'mark_conversation_read(bigint)',
    'toggle_message_reaction(bigint,text)',
    'visible_moments()',
    'create_moment(text,text,text,text,text)',
    'delete_moment(bigint)',
    'view_moment(bigint)',
    'react_to_moment(bigint,text)',
    'reply_to_moment(bigint,text)',
    'list_notifications()',
    'list_blocks()',
    'badges()',
    'delete_account(text)'
  ]
  loop
    execute format('revoke all on function public.%s from public, anon;', fn);
    execute format('grant execute on function public.%s to authenticated, service_role;', fn);
  end loop;
end $$;

do $$
declare
  fn text;
begin
  foreach fn in array array[
    'crushly_fail(integer,text,text)',
    'serialize_message(public.messages,bigint,boolean)',
    'serialize_moment(public.moments,bigint)',
    'public_profile(bigint,bigint,boolean)',
    'load_visible_profile(bigint,bigint,boolean)',
    'peer_summary(bigint,bigint)',
    'messaging_block_reason(bigint,bigint)',
    'can_view_moment(public.moments,bigint)',
    'ensure_conversation(bigint,bigint)',
    'notify_to(bigint,text,bigint,bigint,text)',
    'photos_of(bigint)',
    'receipts_visible(bigint,bigint)',
    'is_blocked_pair(bigint,bigint)',
    'is_connected_pair(bigint,bigint)',
    'connect_pair(bigint,bigint)',
    'disconnect_pair(bigint,bigint)',
    'notification_allowed(bigint,text)'
  ]
  loop
    execute format('revoke all on function public.%s from public, anon, authenticated;', fn);
  end loop;
end $$;

-- me_id() is read by RLS policies, so members must be able to execute it
-- (it only ever returns their own id — or null).
grant execute on function public.me_id() to anon, authenticated, service_role;

-- ================================ 20261008000003_storage.sql

-- Storage: one public bucket for everything the app shows (profile photos,
-- chat media, Moment media, demo seed photos) and one private bucket for
-- verification selfies (only the member themself — and moderators via the
-- service role — can read them).
--
-- Path convention for user media: <kind>/<profile id>/<file>
--   photos/123/abc.jpg  moments/123/xyz.jpg  messages/123/clip.m4a
-- Demo seed photos live under seed/<name>.jpg (uploaded by
-- supabase/scripts/seed-storage.mjs with the service role).

insert into storage.buckets (id, name, public)
values ('media', 'media', true), ('verification', 'verification', false)
on conflict (id) do nothing;

create policy "media_public_read" on storage.objects
  for select to public using (bucket_id = 'media');

create policy "media_insert_own" on storage.objects
  for insert to authenticated with check (
    bucket_id = 'media'
    and (storage.foldername(name))[1] in ('photos', 'moments', 'messages')
    and (storage.foldername(name))[2] = public.me_id()::text
  );

create policy "media_delete_own" on storage.objects
  for delete to authenticated using (
    bucket_id = 'media'
    and (storage.foldername(name))[1] in ('photos', 'moments', 'messages')
    and (storage.foldername(name))[2] = public.me_id()::text
  );

create policy "verification_self_read" on storage.objects
  for select to authenticated using (
    bucket_id = 'verification'
    and (storage.foldername(name))[1] = 'selfies'
    and (storage.foldername(name))[2] = public.me_id()::text
  );

create policy "verification_self_insert" on storage.objects
  for insert to authenticated with check (
    bucket_id = 'verification'
    and (storage.foldername(name))[1] = 'selfies'
    and (storage.foldername(name))[2] = public.me_id()::text
  );
