-- Crushly setup part 8 of 10 (from 20261009000008_private_calls.sql) — generated by npm run bundle:sql.
-- Run the parts in order in the Supabase SQL editor. Re-running is safe.
-- Private Realtime authorization for per-call signaling. Tokens are generated
-- server-side, never overwritten, and bound to the two conversation members.
create table if not exists public.call_rooms (
  channel text primary key,
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  caller_id bigint not null references public.profiles(id) on delete cascade,
  callee_id bigint not null references public.profiles(id) on delete cascade,
  created_at bigint not null default public.now_ms(),
  expires_at bigint not null default public.now_ms() + 7200000,
  closed_at bigint
);
alter table public.call_rooms enable row level security;
revoke all on public.call_rooms from anon, authenticated;

create or replace function public.register_call_room(p_conversation_id bigint) returns text
language plpgsql security definer set search_path = public as $$
declare
  me bigint := public.me_id();
  conv record;
  peer bigint;
  token text := 'call-' || replace(gen_random_uuid()::text, '-', '');
begin
  if me is null then perform public.crushly_fail(401, '', 'Sign in again to make calls.'); end if;
  select * into conv from public.conversations where id = p_conversation_id;
  if not found or me not in (conv.user_a, conv.user_b) then
    perform public.crushly_fail(404, '', 'Conversation not found.');
  end if;
  peer := case when conv.user_a = me then conv.user_b else conv.user_a end;
  if conv.closed or public.messaging_block_reason(me, peer) is not null then
    perform public.crushly_fail(403, '', 'Calling is not available in this conversation.');
  end if;
  -- Serialize per-caller creation to make the rate limit safe under concurrency.
  perform pg_advisory_xact_lock(me);
  if (select count(*) from public.call_rooms where caller_id = me and created_at > public.now_ms() - 60000) >= 5 then
    perform public.crushly_fail(429, '', 'Too many calls. Wait a minute and try again.');
  end if;
  delete from public.call_rooms where expires_at < public.now_ms() - 86400000;
  insert into public.call_rooms(channel, conversation_id, caller_id, callee_id) values(token, conv.id, me, peer);
  return token;
end $$;
revoke all on function public.register_call_room(bigint) from public, anon;
grant execute on function public.register_call_room(bigint) to authenticated;

create or replace function public.can_join_call(p_channel text) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.call_rooms r join public.conversations c on c.id = r.conversation_id
    where r.channel = p_channel and r.expires_at > public.now_ms() and r.closed_at is null
      and public.me_id() in (r.caller_id, r.callee_id)
      and not c.closed and public.messaging_block_reason(r.caller_id, r.callee_id) is null
  )
$$;
revoke all on function public.can_join_call(text) from public, anon;
grant execute on function public.can_join_call(text) to authenticated;

create or replace function public.end_call_room(p_channel text) returns void
language sql security definer set search_path = public as $$
  update public.call_rooms set closed_at = public.now_ms()
    where channel = p_channel and public.me_id() in (caller_id, callee_id) and closed_at is null
$$;
revoke all on function public.end_call_room(text) from public, anon;
grant execute on function public.end_call_room(text) to authenticated;

-- Supabase supplies realtime.messages and realtime.topic(). Plain-Postgres
-- smoke tests supply faithful minimal stubs for authorization checks.
drop policy if exists "crushly_call_receive" on realtime.messages;
create policy "crushly_call_receive" on realtime.messages
  for select to authenticated using (extension = 'broadcast' and public.can_join_call(realtime.topic()));
drop policy if exists "crushly_call_send" on realtime.messages;
create policy "crushly_call_send" on realtime.messages
  for insert to authenticated with check (extension = 'broadcast' and public.can_join_call(realtime.topic()));

-- Even a custom client cannot invite someone into an unrelated/unregistered room.
create or replace function public.validate_call_invitation() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if new.kind = 'call' and not exists (
    select 1 from public.call_rooms r where r.channel = new.meta ->> 'channel'
      and r.conversation_id = new.conversation_id and r.caller_id = new.sender_id
      and r.closed_at is null and r.expires_at > public.now_ms()
  ) then
    perform public.crushly_fail(400, '', 'This call invitation has expired. Start a new call.');
  end if;
  return new;
end $$;
drop trigger if exists validate_call_invitation on public.messages;
create trigger validate_call_invitation before insert on public.messages
  for each row execute function public.validate_call_invitation();
